### ISSUE TITLE
Rewriting proto scripts in Python

### ISSUE THREAD

**Issue by Avasam** [python/typeshed#12511]
I've hinted at it previously, I am now officially suggesting we rewrite the shell scripts found in `scripts` in Python instead.
- They only worked\* on Linux (now MacOS)
  - Attempting to make them work on MacOS, @sobolevn accidentally broke the sed command in https://github.com/python/typeshed/pull/12330
  - since the difference is in quote, I don't see a clean way to reconcile the commands by, for example, storing the command in a variable.
- We require additional tools to be installed that are not in our dev requirements (wget on mac, unzip on ubuntu, wsl on Windows)
- We could speed up the runs by using UV as we could assume deps in `requirements-tests.txt` have been installed (if we even decide to still create a different venv, rather than consolidating mypy-protobuf versions)
- It's extremely slow on Windows WSL2 because it just has very slow disk operations across the VM boundary (https://github.com/microsoft/WSL/issues/4197#issuecomment-604592340 & https://learn.microsoft.com/en-us/windows/wsl/compare-versions#comparing-features)
- Our existing tooling could do some basic checks on the scripts.

I am opening this issue to share my intention, but I doubt there'd be much opposition ^^" If anyone would like to take this, let me know, otherwise I'll probably do it sometimes within the next week.

**Comment by Avasam** [comment]
Unless I'm doing something really wrong, looks like Python's tarfile module is unable to open GitHub source code archives. Despite the "tarfile" utility and Windows being able to.
```
Downloading 'https://github.com/Blizzard/s2client-proto/archive/c04df4adbe274858a4eb8417175ee32ad02fd609.zip' to 'C:\Users\Avasam\AppData\Local\Temp\tmpziwp2ahj\c04df4adbe274858a4eb8417175ee32ad02fd609.zip'
Extracting 'C:\Users\Avasam\AppData\Local\Temp\tmpziwp2ahj\c04df4adbe274858a4eb8417175ee32ad02fd609.zip' to '.'
Traceback (most recent call last):
  File "E:\Users\Avasam\Documents\Git\typeshed\scripts\protobuf\s2clientprotocol.py", line 73, in <module>
    main()
  File "E:\Users\Avasam\Documents\Git\typeshed\scripts\protobuf\s2clientprotocol.py", line 41, in main
    extract_archive(archive_path, double_compressed=True)
  File "E:\Users\Avasam\Documents\Git\typeshed\scripts\protobuf\_helpers.py", line 33, in extract_archive
    with tarfile.open(archive_path) as file_in:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Avasam\AppData\Local\Programs\Python\Python312\Lib\tarfile.py", line 1808, in open
    raise ReadError(f"file could not be opened successfully:\n{error_msgs_summary}")
tarfile.ReadError: file could not be opened successfully:
- method gz: ReadError('not a gzip file')
- method bz2: ReadError('not a bzip2 file')
- method xz: ReadError('not an lzma file')
- method tar: ReadError('invalid header')
```

Code snippet to try:
```
def download_file(url: str | bytes, destination: FileDescriptorOrPath) -> None:
    print(f"Downloading {url!r} to '{destination}'")
    resp = requests.get(url, stream=True)
    if resp.status_code != 200:
        raise RuntimeError(f"Error downloading {url}")
    with open(destination, "wb") as file:
        file.write(resp.raw.read())


def extract_archive(archive_path: StrPath, destination: StrOrBytesPath = ".") -> None:
    print(f"Extracting '{archive_path}' to '{destination}'")
    with tarfile.open(archive_path) as file_in:
        if hasattr(tarfile, "data_filter"):
            file_in.extraction_filter = tarfile.data_filter
        file_in.extractall(destination)

S2CLIENT_PROTO_VERSION = "c04df4adbe274858a4eb8417175ee32ad02fd609"
S2CLIENT_PROTO_FILENAME = f"{S2CLIENT_PROTO_VERSION}.zip"
S2CLIENT_PROTO_URL = f"https://github.com/Blizzard/s2client-proto/archive/{S2CLIENT_PROTO_FILENAME}"

temp_dir = Path(tempfile.mkdtemp())
# Fetch s2clientprotocol (which contains all the .proto files)
archive_path = temp_dir / S2CLIENT_PROTO_FILENAME
download_file(S2CLIENT_PROTO_URL, archive_path)
extract_archive(archive_path)
```
