### ISSUE TITLE
specially crafted __repr__ signiture causes mypy to terminate with an "Internal Error"

### ISSUE THREAD

**Issue by gossrock** [python/typeshed#2358]
I can re-post this error over on the mypy project if it turns out it's more appropriate there.

I discovered this bug mainly because I didn't know how ``__repr__`` was supposed to work. 
This line (even if it's the only line in the python file):
```
def __rpow__(self, x:int, mod:int = None) -> int: ...
```

produces this output:
```
./arbitrary_base_math_bug.py:5: error: INTERNAL ERROR -- please report a bug at https://github.com/python/mypy/issues version: 0.620
Traceback (most recent call last):
  File "/home/peter/Documents/scratch_code/.venv/bin/mypy", line 11, in <module>
    sys.exit(console_entry())
  File "/home/peter/Documents/scratch_code/.venv/lib/python3.7/site-packages/mypy/__main__.py", line 7, in console_entry
    main(None)
  File "/home/peter/Documents/scratch_code/.venv/lib/python3.7/site-packages/mypy/main.py", line 91, in main
    res = type_check_only(sources, bin_dir, options, flush_errors, fscache)  # noqa
  File "/home/peter/Documents/scratch_code/.venv/lib/python3.7/site-packages/mypy/main.py", line 148, in type_check_only
    fscache=fscache)
  File "/home/peter/Documents/scratch_code/.venv/lib/python3.7/site-packages/mypy/build.py", line 177, in build
    flush_errors, fscache)
  File "/home/peter/Documents/scratch_code/.venv/lib/python3.7/site-packages/mypy/build.py", line 350, in _build
    graph = dispatch(sources, manager)
  File "/home/peter/Documents/scratch_code/.venv/lib/python3.7/site-packages/mypy/build.py", line 2560, in dispatch
    process_graph(graph, manager)
  File "/home/peter/Documents/scratch_code/.venv/lib/python3.7/site-packages/mypy/build.py", line 2853, in process_graph
    process_stale_scc(graph, scc, manager)
  File "/home/peter/Documents/scratch_code/.venv/lib/python3.7/site-packages/mypy/build.py", line 2976, in process_stale_scc
    graph[id].type_check_first_pass()
  File "/home/peter/Documents/scratch_code/.venv/lib/python3.7/site-packages/mypy/build.py", line 2151, in type_check_first_pass
    self.type_checker().check_first_pass()
  File "/home/peter/Documents/scratch_code/.venv/lib/python3.7/site-packages/mypy/checker.py", line 253, in check_first_pass
    self.accept(d)
  File "/home/peter/Documents/scratch_code/.venv/lib/python3.7/site-packages/mypy/checker.py", line 352, in accept
    stmt.accept(self)
  File "/home/peter/Documents/scratch_code/.venv/lib/python3.7/site-packages/mypy/nodes.py", line 591, in accept
    return visitor.visit_func_def(self)
  File "/home/peter/Documents/scratch_code/.venv/lib/python3.7/site-packages/mypy/checker.py", line 663, in visit_func_def
    self._visit_func_def(defn)
  File "/home/peter/Documents/scratch_code/.venv/lib/python3.7/site-packages/mypy/checker.py", line 667, in _visit_func_def
    self.check_func_item(defn, name=defn.name())
  File "/home/peter/Documents/scratch_code/.venv/lib/python3.7/site-packages/mypy/checker.py", line 729, in check_func_item
    self.check_func_def(defn, typ, name)
  File "/home/peter/Documents/scratch_code/.venv/lib/python3.7/site-packages/mypy/checker.py", line 779, in check_func_def
    self.check_reverse_op_method(item, typ, name, defn)
  File "/home/peter/Documents/scratch_code/.venv/lib/python3.7/site-packages/mypy/checker.py", line 1006, in check_reverse_op_method
    assert len(reverse_type.arg_types) == 2
AssertionError: 
./arbitrary_base_math_bug.py:5: : note: use --pdb to drop into pdb
```

these very similar but slightly different lines will cause various warnings but will not cause the above problem:
```
def __rpow__(self, x:int, mod:int = None): ...
def __rpow__(self, x:int, mod:int) -> int: ...
def __rpow__(x:int, mod:int = None) -> int: ...
def __rpow2__(self, x:int, mod:int = None) -> int: ...
```

**Comment by gvanrossum** [comment]
Yeah, this definitely belongs in the mypy tracker. Note that on master it crashes with a different traceback, because that assert was changed to `>= 2` by https://github.com/python/mypy/pull/5348. (@srittau take note)

**Comment by gossrock** [comment]
Thanks, I have moved it over to mypy as https://github.com/python/mypy/issues/5419
