### ISSUE TITLE
contextlib.contextmanager allows `Iterator[T]` -- should probably be `Generator[T, None, None]`?

### ISSUE THREAD

**Issue by asottile** [python/typeshed#2772]
For instance, this script passes mypy:

```python
import contextlib
from typing import Iterator

@contextlib.contextmanager
def f() -> Iterator[int]:
    return iter([1])


with f():
    pass


with f():
    raise TypeError('wat')
```

but fails at runtime (and not in the expected way):

```console
$ python t.py 
Traceback (most recent call last):
  File "t.py", line 14, in <module>
    raise TypeError('wat')
TypeError: wat

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "t.py", line 14, in <module>
    raise TypeError('wat')
  File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
AttributeError: 'list_iterator' object has no attribute 'throw'
```

**Comment by graingert** [comment]
contextlib.contextmanager doesn't need to be as specific as `Generator[T, None, None]`, it could take the slightly wider type:

```python
class ContextManagerArgReturnType(Protocol, Generic[T]):
    def __next__(self) -> T: ...
    def throw(\, self, exctype: Optional[Type[BaseException]], excinst: Optional[BaseException], exctb: Optional[TracebackType]) -> Any: ...

ContextManagerArgType = Callable[[], ContextManagerArgReturnType[T]]
```

**Comment by asottile** [comment]
this (unfortunately) caused a production incident today -- any chance this can be reconsidered (despite the backward incompatibility)?

**Comment by HacKanCuBa** [comment]
So, this is an interesting pitfall of using `Iterator[]` instead of `Generator[]` as [the docs suggest](https://docs.python.org/3/library/typing.html#typing.Generator):
> A generator can be annotated by the generic type Generator[YieldType, SendType, ReturnType]
> ...
> Alternatively, annotate your generator as having a return type of either Iterable[YieldType] or Iterator[YieldType]

I'm just bumping this up.

**Comment by AlexWaygood** [comment]
Marking as deferred unless/until PEP 696 is accepted, as per https://github.com/python/typeshed/pull/7430#issuecomment-1238711970.

**Comment by srittau** [comment]
See #11422 for the type var generics feature tracker.

**Comment by hauntsaninja** [comment]
Note that while PEP 696 will help some ergonomic issues and therefore could be good to re-assess, I'm still pretty strongly disinclined to change this. It's been 1.5 years since I commented in https://github.com/python/typeshed/pull/7430#issuecomment-1238711970 asking people to report real-life false negatives and no one else has (I just went through all the issues that link to this one and I don't remember any mypy issue reports either). A ruff lint with autofix could help, as would Jukka's suggestion here: https://github.com/python/typeshed/pull/7430#issuecomment-1080460175

**Comment by max-muoto** [comment]
Now that we have PEP 696, a PR experimenting with the effects here: https://github.com/python/typeshed/pull/12334
