### ISSUE TITLE
CI fails for `3.9.8`

### ISSUE THREAD

**Issue by sobolevn** [python/typeshed#6280]
Link: https://github.com/python/typeshed/runs/4187694837?check_suite_focus=true
Output: 

```
Traceback (most recent call last):
  File "/home/runner/work/typeshed/typeshed/./tests/pytype_test.py", line 20, in <module>
    from pytype import config as pytype_config, load_pytd
  File "/opt/hostedtoolcache/Python/3.9.8/x64/lib/python3.9/site-packages/pytype/config.py", line 14, in <module>
    from pytype import errors
  File "/opt/hostedtoolcache/Python/3.9.8/x64/lib/python3.9/site-packages/pytype/errors.py", line 13, in <module>
    from pytype import matcher
  File "/opt/hostedtoolcache/Python/3.9.8/x64/lib/python3.9/site-packages/pytype/matcher.py", line 14, in <module>
    from pytype.overlays import typing_overlay
  File "/opt/hostedtoolcache/Python/3.9.8/x64/lib/python3.9/site-packages/pytype/overlays/typing_overlay.py", line 13, in <module>
    from pytype.overlays import collections_overlay
  File "/opt/hostedtoolcache/Python/3.9.8/x64/lib/python3.9/site-packages/pytype/overlays/collections_overlay.py", line 11, in <module>
    from pytype.pyi import parser
  File "/opt/hostedtoolcache/Python/3.9.8/x64/lib/python3.9/site-packages/pytype/pyi/parser.py", line 11, in <module>
    from pytype.pyi import classdef
  File "/opt/hostedtoolcache/Python/3.9.8/x64/lib/python3.9/site-packages/pytype/pyi/classdef.py", line 7, in <module>
    from pytype.pyi.types import ParseError  # pylint: disable=g-importing-member
  File "/opt/hostedtoolcache/Python/3.9.8/x64/lib/python3.9/site-packages/pytype/pyi/types.py", line 11, in <module>
    from typed_ast import ast3
  File "/opt/hostedtoolcache/Python/3.9.8/x64/lib/python3.9/site-packages/typed_ast/ast3.py", line 40, in <module>
    from typed_ast import _ast3
ImportError: /opt/hostedtoolcache/Python/3.9.8/x64/lib/python3.9/site-packages/typed_ast/_ast3.cpython-39-x86_64-linux-gnu.so: undefined symbol: _PyUnicode_DecodeUnicodeEscape
```

I've already seen a lot of similar failures on other project. My recommendation is to pin python to `3.9.7` version, until `3.9.9` is released.

I will send a PR shortly.

**Comment by srittau** [comment]
Should be fixed by #6278.
