### ISSUE TITLE
imaplib.Internaldate2tuple's argument type is wrong

### ISSUE THREAD

**Issue by svenpanne** [python/typeshed#7781]
Typeshed claims that it must be a `str`, but this should actually be `bytes`:
```
baz@foobar:~$ python3
Python 3.9.7 (default, Sep 10 2021, 14:59:43) 
[GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import imaplib
>>> imaplib.Internaldate2tuple(b'25 (INTERNALDATE "01-Apr-2000 19:02:23 -0700")')
time.struct_time(tm_year=2000, tm_mon=4, tm_mday=2, tm_hour=4, tm_min=2, tm_sec=23, tm_wday=6, tm_yday=93, tm_isdst=1)
>>> imaplib.Internaldate2tuple('25 (INTERNALDATE "01-Apr-2000 19:02:23 -0700")')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.9/imaplib.py", line 1453, in Internaldate2tuple
    mo = InternalDate.match(resp)
TypeError: cannot use a bytes pattern on a string-like object
```

**Comment by srittau** [comment]
PR welcome!
