### ISSUE TITLE
mypy-primer is failing on PRs

### ISSUE THREAD

**Issue by AlexWaygood** [python/typeshed#8677]
See, e.g.:

- https://github.com/python/typeshed/pull/8676
- https://github.com/python/typeshed/pull/8654
- https://github.com/python/typeshed/pull/8678

**Comment by AlexWaygood** [comment]
The traceback in https://github.com/python/typeshed/runs/8169182086?check_suite_focus=true is:

```
new commit
commit b128bb3a53378ef78fd1176a928103fc1d12a830
Merge bc0bb3017f045b6601bac179cccb58fde5e[31](https://github.com/python/typeshed/runs/8169182086?check_suite_focus=true#step:5:32)f04 into 61831c0164ecfb70dcb2ea113e635a3c03dc78ed
Previous HEAD position was b128bb3a Merge bc0bb3017f045b6601bac179cccb58fde5e31f04 into 61831c0164ecfb70dcb2ea113e635a3c03dc78ed
Switched to a new branch 'upstream_master'
branch 'upstream_master' set up to track 'origin/master'.
base commit
commit 61831c0164ecfb70dcb2ea113e635a3c03dc78ed
Add some undocumented constants to gzip.pyi (#8675)

/tmp/mypy_primer/new_mypy/venv/bin/pip install mypy==v0.971
/tmp/mypy_primer/old_mypy/venv/bin/pip install mypy==v0.971
/tmp/mypy_primer/new_mypy/venv/bin/mypy --version
/tmp/mypy_primer/old_mypy/venv/bin/mypy --version
new mypy version: mypy 0.971 (compiled: yes)
old mypy version: mypy 0.971 (compiled: yes)
git clone --recurse-submodules /home/runner/work/typeshed/typeshed/typeshed_to_test	 in /tmp/mypy_primer/new_typeshed
git checkout --force --recurse-submodules origin/HEAD	 in /tmp/mypy_primer/new_typeshed/typeshed_to_test
git branch -D b128bb3a5[33](https://github.com/python/typeshed/runs/8169182086?check_suite_focus=true#step:5:34)78ef78fd1176a928103fc1d12a830	 in /tmp/mypy_primer/new_typeshed/typeshed_to_test
git checkout --force --recurse-submodules b128bb3a53378ef78fd1176a928103fc1d12a830	 in /tmp/mypy_primer/new_typeshed/typeshed_to_test
git clone --recurse-submodules /home/runner/work/typeshed/typeshed/typeshed_to_test	 in /tmp/mypy_primer/old_typeshed
git checkout --force --recurse-submodules origin/HEAD	 in /tmp/mypy_primer/old_typeshed/typeshed_to_test
git branch -D upstream_master	 in /tmp/mypy_primer/old_typeshed/typeshed_to_test
git checkout --force --recurse-submodules upstream_master	 in /tmp/mypy_primer/old_typeshed/typeshed_to_test
git clone --recurse-submodules https://github.com/jaraco/zipp --depth 1	 in /tmp/mypy_primer/projects
git clone --recurse-submodules https://github.com/python-jsonschema/check-jsonschema --depth 1	 in /tmp/mypy_primer/projects
git clone --recurse-submodules https://github.com/niklasf/python-chess --depth 1	 in /tmp/mypy_primer/projects
git clone --recurse-submodules https://github.com/pypa/pip --depth 1	 in /tmp/mypy_primer/projects
git clone --recurse-submodules https://github.com/pytorch/vision --depth 1	 in /tmp/mypy_primer/projects
git clone --recurse-submodules https://github.com/aio-libs/yarl --depth 1	 in /tmp/mypy_primer/projects
git clone --recurse-submodules https://github.com/tornadoweb/tornado --depth 1	 in /tmp/mypy_primer/projects
git clone --recurse-submodules https://github.com/pydata/xarray --depth 1	 in /tmp/mypy_primer/projects
git clone --recurse-submodules https://github.com/streamlit/streamlit --depth 1	 in /tmp/mypy_primer/projects
git clone --recurse-submodules https://github.com/johtso/httpx-caching --depth 1	 in /tmp/mypy_primer/projects
git clone --recurse-submodules https://github.com/mikeshardmind/SinbadCogs --depth 1	 in /tmp/mypy_primer/projects
git clone --recurse-submodules https://github.com/bokeh/bokeh --depth 1	 in /tmp/mypy_primer/projects
git clone --recurse-submodules https://github.com/FasterSpeeding/Tanjun --depth 1	 in /tmp/mypy_primer/projects
git clone --recurse-submodules https://github.com/dedupeio/dedupe --depth 1	 in /tmp/mypy_primer/projects
git clone --recurse-submodules https://github.com/yurijmikhalevich/rclip --depth 1	 in /tmp/mypy_primer/projects
git clone --recurse-submodules https://github.com/Akuli/porcupine --depth 1	 in /tmp/mypy_primer/projects
git clone --recurse-submodules https://gitlab.com/dkg/python-sop --depth 1	 in /tmp/mypy_primer/projects
git clone --recurse-submodules https://github.com/jab/bidict --depth 1	 in /tmp/mypy_primer/projects
git clone --recurse-submodules https://github.com/DataDog/dd-trace-py --depth 1	 in /tmp/mypy_primer/projects
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/mypy_primer.py", line 940, in main
    retcode = inner()
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/mypy_primer.py", line 933, in inner
    retcode = asyncio.run(coro)
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/mypy_primer.py", line 753, in primer
    result = await result_fut
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/asyncio/tasks.py", line 571, in _wait_for_one
    return f.result()  # May raise f.exception().
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/mypy_primer.py", line 414, in primer_result
    await self.setup()
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/mypy_primer.py", line [34](https://github.com/python/typeshed/runs/8169182086?check_suite_focus=true#step:5:35)5, in setup
    repo_dir = await ensure_repo_at_revision(
  File "/opt/hostedtoolcache/Python/3.10.6/x[64](https://github.com/python/typeshed/runs/8169182086?check_suite_focus=true#step:5:65)/lib/python3.10/site-packages/mypy_primer.py", line 1[68](https://github.com/python/typeshed/runs/8169182086?check_suite_focus=true#step:5:69), in ensure_repo_at_revision
    await clone(repo_url, cwd, shallow=revision_like is None)
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/mypy_primer.py", line 134, in clone
    await run(cmd, cwd=cwd)
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/mypy_primer.py", line 110, in run
    raise subprocess.CalledProcessError(proc.returncode, cmd, output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['git', 'clone', '--recurse-submodules', 'https://gitlab.com/dkg/python-sop', '--depth', '1']' returned non-zero exit status 128.
```

**Comment by AlexWaygood** [comment]
https://github.com/python/typeshed/runs/8169182218?check_suite_focus=true has the same error, but for `aiohttp` rather than `dd-trace`.

**Comment by sobolevn** [comment]
<img width="1280" alt="Снимок экрана 2022-09-03 в 15 58 28" src="https://user-images.githubusercontent.com/4660275/188271503-faec7093-8d00-43fc-b0e7-128853c50dc9.png">

The reason is: gitlab is down

**Comment by AlexWaygood** [comment]
> <img alt="Снимок экрана 2022-09-03 в 15 58 28" width="1280" src="https://user-images.githubusercontent.com/4660275/188271503-faec7093-8d00-43fc-b0e7-128853c50dc9.png">
> 
> The reason is: gitlab is down

...That makes sense!
