### ISSUE TITLE
I can't import _typeshed.

### ISSUE THREAD

**Issue by hktzx** [python/typeshed#9480]
I want to use dateutil,
```bash
\dateutil\parser\isoparser.py
```
```python
from _typeshed import SupportsRead # I can't import it.
from datetime import date, datetime, time, tzinfo
from typing import Text, Union

_Readable = SupportsRead[Union[Text, bytes]]
_TakesAscii = Union[Text, bytes, _Readable]

class isoparser:
    def __init__(self, sep: Text | bytes | None = ...): ...
    def isoparse(self, dt_str: _TakesAscii) -> datetime: ...
    def parse_isodate(self, datestr: _TakesAscii) -> date: ...
    def parse_isotime(self, timestr: _TakesAscii) -> time: ...
    def parse_tzstr(self, tzstr: _TakesAscii, zero_as_utc: bool = ...) -> tzinfo: ...

def isoparse(dt_str: _TakesAscii) -> datetime: ...
```
But when I run it,it give me a error:
```bash
Traceback (most recent call last):
  File "car.py", line 1, in <module>
    import matplotlib.pyplot as plt  
  File "C:\Users\duo'duo'lan\AppData\Local\Programs\Python\Python38\lib\site-packages\matplotlib\pyplot.py", line 60, in <module>
    from matplotlib.figure import Figure, FigureBase, figaspect
  File "C:\Users\duo'duo'lan\AppData\Local\Programs\Python\Python38\lib\site-packages\matplotlib\figure.py", line 26, in <module>
    from matplotlib import _blocking_input, backend_bases, _docstring, projections
  File "C:\Users\duo'duo'lan\AppData\Local\Programs\Python\Python38\lib\site-packages\matplotlib\projections\__init__.py", line 55, in <module>
    from .. import axes, _docstring
  File "C:\Users\duo'duo'lan\AppData\Local\Programs\Python\Python38\lib\site-packages\matplotlib\axes\__init__.py", line 1, in <module>
    from ._subplots import *
  File "C:\Users\duo'duo'lan\AppData\Local\Programs\Python\Python38\lib\site-packages\matplotlib\axes\_subplots.py", line 3, in <module>
    from matplotlib.axes._axes import Axes
  File "C:\Users\duo'duo'lan\AppData\Local\Programs\Python\Python38\lib\site-packages\matplotlib\axes\_axes.py", line 11, in <module>
    import matplotlib.category  # Register category unit converter as side-effect.
  File "C:\Users\duo'duo'lan\AppData\Local\Programs\Python\Python38\lib\site-packages\matplotlib\category.py", line 14, in <module>
    import dateutil.parser
  File "C:\Users\duo'duo'lan\AppData\Local\Programs\Python\Python38\lib\site-packages\dateutil\parser\__init__.py", line 4, in <module>
    from .isoparser import isoparse as isoparse, isoparser as isoparser
  File "C:\Users\duo'duo'lan\AppData\Local\Programs\Python\Python38\lib\site-packages\dateutil\parser\isoparser.py", line 1, in <module>
    from _typeshed import SupportsRead
ModuleNotFoundError: No module named '_typeshed'
```
I don't know how to use _typeshed.
How to install _typeshed?
thanks.

**Comment by JelleZijlstra** [comment]
`_typeshed` cannot be imported at runtime; it's purely a stub. You can use it in type annotations with code like:

```python
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from _typeshed import SupportsRead

def some_function(f: "SupportsRead") -> None: ...
```
